<<<<<<< HEAD
collections_config:
  site_data:
    path: src/data
=======
collections_config: 
      site_data: 
        path: src/data
      pages:
        path: src/pages
        url: '/[full_slug]/'
        output: true
        icon: laptop_mac
        _enabled_editors:
          - visual
        filter:
          base: strict
        add_options:
          - name: Add New Page
            schema: default
            icon: pages
        schemas:
          default:
            name: New Page
            path: schemas/page.md
            remove_extra_inputs: false
        create:
          path: '[relative_base_path]/{title|slugify}.md'
>>>>>>> parent of e9bf91a (Update cloudcannon.config.yml)

      
collection_groups:
  pages:
    path: src/pages
    type: astro

data_config:
<<<<<<< HEAD
<<<<<<< HEAD
  collections:
    - pages

source:
  src: src

inputs:
=======

source: 

_inputs:
>>>>>>> parent of d6e4e36 (Update cloudcannon.config.yml)
  src:
    type: image
=======
  data:
      path: src/data
      type: json

source: 
  _inputs:
    src:
      type: image
>>>>>>> parent of e9bf91a (Update cloudcannon.config.yml)

paths:
  static: ""
  uploads: uploads

source_editor:
<<<<<<< HEAD
  timezone: Etc/UTC
=======

timezone: Etc/UTC

>>>>>>> parent of e9bf91a (Update cloudcannon.config.yml)
