collections_config: 
      site_data: 
        path: src/data

collection_groups:

data_config:

source: 

_inputs:
  src:
    type: image

paths:
  static: ''
  uploads: uploads

source_editor:

timezone: Etc/UTC

