paths:
  data: data
  static: "public"
  uploads: public/images

collections_config:
  pages:
    path: src/content/pages
    url: "/[full_slug]/"
    output: true
    icon: laptop_mac
    _enabled_editors:
      - visual
    filter:
      base: strict

collection_groups:
  - heading: Pages
    collections:
      - pages

# Input config
_inputs:
  gallery_images:
    type: array
    label: Gallery Images
    add_label: "Add Image"
  gallery_images[*]:
    type: image
    fields:
      - type: image
        name: src
        label: Image File
        upload: true
        path: "public/images"
      - type: text
        name: alt