collections_config:
  site_data:
    path: src/data

collection_groups:
  pages:
    path: src/pages
    type: astro

data_config:
<<<<<<< HEAD
  collections:
    - pages

source:
  src: src

inputs:
=======

source: 

_inputs:
>>>>>>> parent of d6e4e36 (Update cloudcannon.config.yml)
  src:
    type: image

paths:
  static: ""
  uploads: uploads

source_editor:
  timezone: Etc/UTC
