collections_config: 
    gallery: 
        path: src/pages

collection_groups:

data_config:

source: 


paths:
  data: ''
  collections: ''
  layouts: null
  static: ''
  uploads: uploads

source_editor:

timezone: Etc/UTC

