paths:
  data: data
  static: public
  uploads: public/uploads

data_config:
  # Removed blog-tags since it references a non-existent file
  # Remove or adjust data configuration as necessary

collections_config:
  data:
    path: data
    disable_add: true
    disable_add_folder: true
    filter:
      exclude: []  # No files are excluded
  pages:
    path: src/pages
    url: "/[slug]/"
    output: true
    icon: wysiwyg
    disable_add_folder: true
    _enabled_editors:
      - visual
    add_options:
      - name: Add New Page
        schema: default
        icon: note_add
    schemas:
      default:
        name: New Page
        path: schemas/page.md
        new_preview_url: "/"
      paginated_collection:
        path: schemas/paginated-collection.md
    _inputs:
      content_blocks:
        empty_type: array
    filter:
      base: strict
  theme_palette:
    path: data 
    output: true 
    icon: color_lens
    _enabled_editors:
      - data 
    disable_add: true
    disable_add_folder: true 
    filter:
      base: none 
      include: []  # No files are included
  site_navigation:
    path: data
    output: true
    icon: table_rows 
    _enabled_editors:
      - data
    disable_add: true
    disable_add_folder: true
    filter:
      base: none
      include: []  # No files are included

collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Site Settings
    collections:
      - data
      - site_navigation
      - theme_palette

_structures:
  content_blocks:
    style: modal
  features:
    values:
      - value:
          item:
          isActive:
  dropdown: 
    values:
      value:
        dropdown_text:
        dropdown_link:
  social:
    values:
      value:
        link: 
        icon: 
        icon_alt:
  sections:
    values:
      value:
        title:
        links:  
  links:
    values:
      value:
        text: 
        link:
  items:
    values: 
      value: 
        link: 
        text: 
        enable_dropdown:
        dropdown:

_inputs:
  thumb_image.image:
    type: image
    options:
      width: 500
      height: 413
      resize_style: crop
  featured_image.image:
    type: image
    options:
      width: 1296
      resize_style: crop
