# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Gallery
  description: A gallery of images for showcasing various content.
  icon: 'photo_library'
  tags:
    - Image
    - Gallery
    - Responsive

# Defines the structure of this component, as well as the default values
blueprint:
  images:
    - "https://ik.imagekit.io/azupnt3mqx/mako-construction-renovation-1.webp"
    - "https://ik.imagekit.io/azupnt3mqx/mako-construction-renovation-2.webp"
    - "https://ik.imagekit.io/azupnt3mqx/mako-construction-renovation-3.webp"
    - "https://ik.imagekit.io/azupnt3mqx/mako-construction-renovation-4.webp"
    - "https://ik.imagekit.io/azupnt3mqx/mako-constuction-renovation-5.jpg"
    - "https://ik.imagekit.io/azupnt3mqx/mako-constuction-renovation-6.jpg"
    - "https://ik.imagekit.io/azupnt3mqx/mako-constuction-renovation-7.jpg"
    - "https://ik.imagekit.io/azupnt3mqx/mako-constuction-renovation-8.jpg"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  images:
    options:
      preview:
        icon: 'image'
        text:
          - 'Gallery Images'
        subtext:
          - 'Update the images in the gallery.'
        image:
          - key: images
